# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/Basys-3-Master.xdc

# Block Designs: bd/uBlaze_pong_im_gen/uBlaze_pong_im_gen.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uBlaze_pong_im_gen || ORIG_REF_NAME==uBlaze_pong_im_gen} -quiet] -quiet

# IP: bd/uBlaze_pong_im_gen/ip/uBlaze_pong_im_gen_pong_image_gen_0_0/uBlaze_pong_im_gen_pong_image_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uBlaze_pong_im_gen_pong_image_gen_0_0 || ORIG_REF_NAME==uBlaze_pong_im_gen_pong_image_gen_0_0} -quiet] -quiet

# IP: bd/uBlaze_pong_im_gen/ip/uBlaze_pong_im_gen_clk_wiz_0_0/uBlaze_pong_im_gen_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uBlaze_pong_im_gen_clk_wiz_0_0 || ORIG_REF_NAME==uBlaze_pong_im_gen_clk_wiz_0_0} -quiet] -quiet

# IP: bd/uBlaze_pong_im_gen/ip/uBlaze_pong_im_gen_microblaze_0_0/uBlaze_pong_im_gen_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uBlaze_pong_im_gen_microblaze_0_0 || ORIG_REF_NAME==uBlaze_pong_im_gen_microblaze_0_0} -quiet] -quiet

# IP: bd/uBlaze_pong_im_gen/ip/uBlaze_pong_im_gen_dlmb_v10_0/uBlaze_pong_im_gen_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uBlaze_pong_im_gen_dlmb_v10_0 || ORIG_REF_NAME==uBlaze_pong_im_gen_dlmb_v10_0} -quiet] -quiet

# IP: bd/uBlaze_pong_im_gen/ip/uBlaze_pong_im_gen_ilmb_v10_0/uBlaze_pong_im_gen_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uBlaze_pong_im_gen_ilmb_v10_0 || ORIG_REF_NAME==uBlaze_pong_im_gen_ilmb_v10_0} -quiet] -quiet

# IP: bd/uBlaze_pong_im_gen/ip/uBlaze_pong_im_gen_dlmb_bram_if_cntlr_0/uBlaze_pong_im_gen_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uBlaze_pong_im_gen_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==uBlaze_pong_im_gen_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/uBlaze_pong_im_gen/ip/uBlaze_pong_im_gen_ilmb_bram_if_cntlr_0/uBlaze_pong_im_gen_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uBlaze_pong_im_gen_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==uBlaze_pong_im_gen_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/uBlaze_pong_im_gen/ip/uBlaze_pong_im_gen_lmb_bram_0/uBlaze_pong_im_gen_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uBlaze_pong_im_gen_lmb_bram_0 || ORIG_REF_NAME==uBlaze_pong_im_gen_lmb_bram_0} -quiet] -quiet

# IP: bd/uBlaze_pong_im_gen/ip/uBlaze_pong_im_gen_mdm_1_0/uBlaze_pong_im_gen_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uBlaze_pong_im_gen_mdm_1_0 || ORIG_REF_NAME==uBlaze_pong_im_gen_mdm_1_0} -quiet] -quiet

# IP: bd/uBlaze_pong_im_gen/ip/uBlaze_pong_im_gen_rst_clk_wiz_0_100M_0/uBlaze_pong_im_gen_rst_clk_wiz_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uBlaze_pong_im_gen_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==uBlaze_pong_im_gen_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/uBlaze_pong_im_gen/ip/uBlaze_pong_im_gen_axi_uartlite_0_0/uBlaze_pong_im_gen_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uBlaze_pong_im_gen_axi_uartlite_0_0 || ORIG_REF_NAME==uBlaze_pong_im_gen_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/uBlaze_pong_im_gen/ip/uBlaze_pong_im_gen_axi_gpio_0_0/uBlaze_pong_im_gen_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uBlaze_pong_im_gen_axi_gpio_0_0 || ORIG_REF_NAME==uBlaze_pong_im_gen_axi_gpio_0_0} -quiet] -quiet

# IP: bd/uBlaze_pong_im_gen/ip/uBlaze_pong_im_gen_xbar_0/uBlaze_pong_im_gen_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uBlaze_pong_im_gen_xbar_0 || ORIG_REF_NAME==uBlaze_pong_im_gen_xbar_0} -quiet] -quiet

# IP: bd/uBlaze_pong_im_gen/ip/uBlaze_pong_im_gen_microblaze_0_axi_periph_0/uBlaze_pong_im_gen_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uBlaze_pong_im_gen_microblaze_0_axi_periph_0 || ORIG_REF_NAME==uBlaze_pong_im_gen_microblaze_0_axi_periph_0} -quiet] -quiet

# XDC: d:/SoCDesign/HW3/hw3_pong_game_v3/hw3_pong_game_v3.gen/sources_1/bd/uBlaze_pong_im_gen/uBlaze_pong_im_gen_ooc.xdc
