# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/SoCDesign/HW3/hw3_pong_game_v3/hw3_pong_game_v3.srcs/sources_1/bd/uBlaze_pong_im_gen/ip/uBlaze_pong_im_gen_rst_clk_wiz_0_100M_0/uBlaze_pong_im_gen_rst_clk_wiz_0_100M_0.xci
# IP: The module: 'uBlaze_pong_im_gen_rst_clk_wiz_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/SoCDesign/HW3/hw3_pong_game_v3/hw3_pong_game_v3.gen/sources_1/bd/uBlaze_pong_im_gen/ip/uBlaze_pong_im_gen_rst_clk_wiz_0_100M_0/uBlaze_pong_im_gen_rst_clk_wiz_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'uBlaze_pong_im_gen_rst_clk_wiz_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/SoCDesign/HW3/hw3_pong_game_v3/hw3_pong_game_v3.gen/sources_1/bd/uBlaze_pong_im_gen/ip/uBlaze_pong_im_gen_rst_clk_wiz_0_100M_0/uBlaze_pong_im_gen_rst_clk_wiz_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'uBlaze_pong_im_gen_rst_clk_wiz_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/SoCDesign/HW3/hw3_pong_game_v3/hw3_pong_game_v3.gen/sources_1/bd/uBlaze_pong_im_gen/ip/uBlaze_pong_im_gen_rst_clk_wiz_0_100M_0/uBlaze_pong_im_gen_rst_clk_wiz_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uBlaze_pong_im_gen_rst_clk_wiz_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/SoCDesign/HW3/hw3_pong_game_v3/hw3_pong_game_v3.srcs/sources_1/bd/uBlaze_pong_im_gen/ip/uBlaze_pong_im_gen_rst_clk_wiz_0_100M_0/uBlaze_pong_im_gen_rst_clk_wiz_0_100M_0.xci
# IP: The module: 'uBlaze_pong_im_gen_rst_clk_wiz_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/SoCDesign/HW3/hw3_pong_game_v3/hw3_pong_game_v3.gen/sources_1/bd/uBlaze_pong_im_gen/ip/uBlaze_pong_im_gen_rst_clk_wiz_0_100M_0/uBlaze_pong_im_gen_rst_clk_wiz_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'uBlaze_pong_im_gen_rst_clk_wiz_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/SoCDesign/HW3/hw3_pong_game_v3/hw3_pong_game_v3.gen/sources_1/bd/uBlaze_pong_im_gen/ip/uBlaze_pong_im_gen_rst_clk_wiz_0_100M_0/uBlaze_pong_im_gen_rst_clk_wiz_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'uBlaze_pong_im_gen_rst_clk_wiz_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/SoCDesign/HW3/hw3_pong_game_v3/hw3_pong_game_v3.gen/sources_1/bd/uBlaze_pong_im_gen/ip/uBlaze_pong_im_gen_rst_clk_wiz_0_100M_0/uBlaze_pong_im_gen_rst_clk_wiz_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uBlaze_pong_im_gen_rst_clk_wiz_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
